### ISSUE TITLE
com.cloudant.client.org.lightcouch.CouchDbException: 400 Bad Request: bad_request: Referer header 

### ISSUE THREAD

**Issue by santooudnur** [icha024/cloudant-spring-boot-starter#2]
I have added document in Couch DB . Example document
{
   "_id": "2505c3877b3b452789e36a0bdb6b87c4",
   "_rev": "1-51ed68335739607895e4b2da802c8760",
   "transaction": {
       "transaction_id": "-11111111",
       "is_json_read": true,
       "is_json_valid": false,
       "has_bmsiw_document": false,
       "bmsiw": {
           "has_bmsiw_data": false,
           "fetched_bmsiw_add_meta_data": false
       },
       "is_json_tansformed": false,
       "is_nlu_processed": false,
       "is_nlu_bmsiw_merged": false
   }
}
Now I have transaction_id with me, based on the same I need to fetch the document and then update the same document in db.

I am trying to use method findByIndex(selector,ClassT) but getting error 
com.cloudant.client.org.lightcouch.CouchDbException: 400 Bad Request: bad_request: Referer header required.
following in selector JSON
{
  "selector": {
    "transaction": {
      "$eq": "-11111111"
    }
  },
  "fields": "[_id, _rev, transaction]"
}

Please let me know the solution for the same

**Comment by icha024** [comment]
Hi @santooudnur, this library is a set of configuration to initiate the underlying library only.

It looks like that exception originate from the library it is using, please raise this with:
https://github.com/cloudant/java-cloudant

Thanks,
Ian

**Comment by santooudnur** [comment]
Issue is with using _ in field name. renamed field names removing _ .it worked.thanks for your information. No issues with library.
