### ISSUE TITLE
Consider adding Spring Boot 2 support

### ISSUE THREAD

**Issue by snicoll** [icha024/cloudant-spring-boot-starter#3]
Relates to https://github.com/spring-projects/spring-boot/issues/13510

We are reviewing our [community starters list](https://github.com/spring-projects/spring-boot/blob/7683d346e31bbe0313a03ce487ee59454665a143/spring-boot-project/spring-boot-starters/README.adoc) and a quick look here suggests that this starter doesn’t yet support Spring Boot 2.

Can you please let us know if/when you plan to support Spring Boot 2?

Thanks!

**Comment by icha024** [comment]
@snicoll I'll take a look at using it with SpringBoot 2 later this week. Sorry been a busy week at work lately

**Comment by icha024** [comment]
@snicoll I've just tested with SpringBoot 2 and it still works fine.

**Comment by snicoll** [comment]
Thanks for the feedback. When do you expect 2.0 to be released?

**Comment by icha024** [comment]
@snicoll the current version works with both SpringBoot 1 and 2. A new release is not required.

Thanks,
Ian

**Comment by snicoll** [comment]
There is a `2.0` milestone you've added on this issue so I am merely asking when this issue is going to be resolved (there's no hurry at all, just wondering).

I understand that manual testing worked but I'd like to know if you intend to release something that builds against Spring Boot 2. I don't really consider manual testing to be enough. 

If you have a CI build that runs against Spring Boot 2, that would be fine as well.

**Comment by icha024** [comment]
The 2.0 milestone was a mistake, have corrected it now as it's no longer required. I'll add some tests for SB2.

**Comment by icha024** [comment]
Actually, it would be easier to do a 2.0 release rather than maintaining compatibility and test with both at the same branch going forward. Added back 2.0 milestone.

**Comment by icha024** [comment]
Tests added and released with PR https://github.com/icha024/cloudant-spring-boot-starter/pull/4

**Comment by snicoll** [comment]
Sweet, thanks!
